selfservice:
  strategies:
    oidc:
      enabled: true
      config:
        providers:
          -
            id: prim
            provider: generic
            client_id: identity-client
            client_secret: identity-secret
            issuer_url: http://127.0.0.1:4444/
            scope:
              - offline
            mapper_url: file://test/e2e/profiles/oidc/prim.jsonnet
          -
            id: google
            provider: generic
            client_id: google-client
            client_secret: identity-secret
            issuer_url: http://127.0.0.1:4444/
            scope:
              - offline
            mapper_url: file://test/e2e/profiles/oidc/prim.jsonnet
          -
            id: github
            provider: generic
            client_id: github-client
            client_secret: identity-secret
            issuer_url: http://127.0.0.1:4444/
            scope:
              - offline
            mapper_url: file://test/e2e/profiles/oidc/prim.jsonnet
